version: '3.3'
services:
  postgres:
    image: postgres:15
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./seed.csv:/seed.csv
    env_file: .env
    ports:
      - '5432:5432'
    container_name: sql-clustering
