version: '3.3'
services:
  postgres:
    image: postgis/postgis:15-3.3-alpine # postgres 15
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./data:/data
    env_file: .env
    ports:
      - '5432:5432'
    container_name: sql-clustering
